config/routes.rb
Invisibility::Application.routes.draw do
	
  root :to => "sessions#new"
  resources :administrators
  resources :users
  resource :session
  resources :parameters
  match '/login' => "sessions#new", :as => "login"
	match '/logout' => "sessions#destroy", :as => "logout"
  match '/statistiques' => 'users#stats', :as => :stats
  match '/dashboard' => 'users#stats', :as => :dashboard
  match '/reports' => "users#reports", :as => :reports
  match '/nombre_de_sms_par_utilisateur' => 'users#nombre_de_sms_par_utilisateur', :as => :nombre_de_sms_par_utilisateur
  match '/sms_par_utilisateur_mail' => 'users#nombre_de_sms_par_utilisateur_mail', :as => :sms_par_utilisateur_mail
  match '/nombre_de_sms_par_couple' => 'users#nombre_de_sms_par_couple', :as => :nombre_de_sms_par_couple
  match '/sms_par_couple_mail' => 'users#nombre_de_sms_par_couple_mail', :as => :sms_par_couple_mail
  match '/send_email' => "users#send_email", :as => :send_email
  match '/write_to_disk' => 'users#write_to_disk', :as => :write_to_disk

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
	has_many :messages
	has_many :relations
	default_scope :order => 'created_at ASC'
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController

	#before_filter :authenticate

  def index 
# récupération des paramètres de la requete
 		@sender = params[:sender]
 		@receiver = params[:receiver]
 		@sms_id = params[:sms_id]
 		@service_id = params[:service_id]
 		@content = params[:content].strip
 		
# compteur
		counter(@sender) 		
 		
 		if in_couple?(@sender)
 			if break_relationship?(@sender, @content)
 				clear_relationship(@sender, @sms_id, @service_id)
 			else
 				forward_message(@sender, @sms_id, @service_id, @content)
 			end
 		else
 					
# accessible aux utilisateurs enregistrés ayant complété leur profil 			
 			if (already_registered?(@sender) && profile_completed?(@sender))
	 			  							
		 			if update_area?(@content, @sender)
		 				update_area(@sender, @sms_id, @service_id, @content)
		 				exit
		 			end
		 			
		 			if infos?(@content, @sender)
		 				if get_infos?(@content)
		 					get_infos(@sender, @sms_id, @service_id, @content)
		 				else
		 					set_infos(@sender, @sms_id, @service_id, @content)
		 				end
		 				exit
		 			end
		 			
		 			if initiate?(@content)
						initiate(@sender, @sms_id, @service_id, @content)
						exit
		 			end
		 			
		 			if accept?(@content)
						accept(@sender, @sms_id, @service_id, @content)
						exit
		 			end
		 			
		 			if research?(@content)
						research(@sender, @sms_id, @service_id, @content)
						exit
		 			end
		 			
		 			error_message(@sender, @sms_id, @service_id, 'Aide') 
	 		end	

# l'utilisateur est enregistré mais n'a pas complété son profil'	 		
	 		if (already_registered?(@sender) && profile_completed?(@sender).eql?(false))
 				complete_profile(@sender, @sms_id, @service_id, @content)
 			end

# l'utilisateur souhaite s'enregistrer 		
 			if registration?(@content)
 				if already_registered?(@sender)
 					already_registered(@sender, @sms_id, @service_id) 
 				else
 					register_user(@sender, @sms_id, @service_id, @content)
 				end								
 			end

# l'utilisateur n'est pas enregistré et ne souhaite pas s'enregistrer 			
 			if already_registered?(@sender).eql?(false) && registration?(@content).eql?(false)
 				error_message(@sender, @sms_id, @service_id, "Veuillez d'abord vous enregistrer et compléter votre profil: Envoyez <tchat mon_pseudo> au 90xxxx")
 			end	
 		end
  end
  
  def stats
  	@parameters = Parameter.first
  	render 'parameters/edit'
  end
  
  def nombre_de_sms_par_utilisateur
  	@users_pagination = Counter.all.paginate(:page => params[:page], :per_page => 10)
  	@users = Counter.all
  	respond_to do |format|
  		format.html
  		format.csv
  	end
  end
  
  def nombre_de_sms_par_utilisateur_mail
  	@users = Counter.all
  	@pseudo = ''
  	CSV.open("#{RAILS_ROOT}/public/attachments/nombre_de_sms_par_utilisateur.csv", "wb", :col_sep => ";") do |csv|
  		csv << ["NUMERO DE TELEPHONE", "PSEUDONYME", "NOMBRE DE SMS ENVOYES"]
  		csv << ["", "", ""]
  		unless @users.eql?(nil)
				@users.each do |user|
					if User.find_by_phone_number(user.phone_number).eql?(nil)
						@pseudo = '-'
					else
						@pseudo = User.find_by_phone_number(user.phone_number).username 
					end 			
					csv << [user.phone_number, @pseudo, user.sms_number]
				end
  		end
		end
		Notifier.send_email('nombre_de_sms_par_utilisateur', current_user.email).deliver
  	redirect_to nombre_de_sms_par_utilisateur_path, :notice => 'Le rapport vous a été envoyé par mail.'
  	File.delete("#{RAILS_ROOT}/public/attachments/nombre_de_sms_par_utilisateur.csv")
  end
  
  def nombre_de_sms_par_couple
  	@users_pagination = Message.find_by_sql("SELECT user_id, receiver, COUNT(content) AS sms_number FROM messages GROUP BY user_id, receiver;").paginate(:page => params[:page], :per_page => 10)
  	@users = Message.find_by_sql("SELECT user_id, receiver, COUNT(content) AS sms_number FROM messages GROUP BY user_id, receiver;")
  	respond_to do |format|
  		format.html
  		format.csv
  	end
  end
  
  def nombre_de_sms_par_couple_mail
  	@users = Message.find_by_sql("SELECT user_id, receiver, COUNT(content) AS sms_number FROM messages GROUP BY user_id, receiver;")
  	CSV.open("#{RAILS_ROOT}/public/attachments/nombre_de_sms_par_couple.csv", "wb", :col_sep => ";") do |csv|
  		csv << ["NUMEROS DE TELEPHONE DU COUPLE", "PSEUDONYMES DU COUPLE", "NOMBRE DE SMS ECHANGES"]
  		csv << ["", "", ""]
  		unless @users.empty?
				@users.each do |user|			
					csv << ["#{User.find_by_id(user.user_id).phone_number} | #{user.receiver}", "#{User.find_by_id(user.user_id).username} | #{User.find_by_phone_number(user.receiver).username}", user.sms_number]
				end
  		end
		end
		Notifier.send_email('nombre_de_sms_par_couple', current_user.email).deliver
  	redirect_to nombre_de_sms_par_utilisateur_path, :notice => 'Le rapport vous a été envoyé par mail.'
  	File.delete("#{RAILS_ROOT}/public/attachments/nombre_de_sms_par_couple.csv")
  end
  
  def reports
  	@users = User.all
  	respond_to do |format|
  		format.html
  		format.csv
  	end
  end
  
  def send_email
  	Notifier.send_email.deliver
  	redirect_to stats_path, :notice => 'email envoyé.'
  	File.delete("#{RAILS_ROOT}/public/attachments/#{Time.now.strftime("%d-%m-%Y")}.csv")
  end
  
  def write_to_disk
  	@users = User.all
  	CSV.open("#{RAILS_ROOT}/public/attachments/#{Time.now.strftime("%d-%m-%Y")}.csv", "wb", :col_sep => ";") do |csv|
  		csv << ["Id", "Username", "Age", "Gender"]
  		@users.each do |user|  			
  			csv << [user.id, user.username, user.age, user.gender]
  		end
		end
		redirect_to send_email_path
  end
  	
# suppression des utilisateurs n'ayant pas complété leur profil deux jours après leur inscription'  
  def delete_latecomers
  	@latecomers = User.where("created_at = updated_at")
  	@latecomers.each do |latecomer|
  		if (Time.now - latecomer.created_at) > 2.days
  			latecomer.destroy
  		end
  	end
  end

end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/nombre_de_sms_par_couple.csv.erb
<% headers = ["NUMEROS DE TELEPHONE DU COUPLE", "PSEUDONYMES DU COUPLE", "NOMBRE DE SMS ECHANGES"] %>
<%= CSV.generate_line headers, {:col_sep => ';'} %>
<% unless @users.eql?(nil) %>
	<% @users.each do |user| %>	
		<% row = [ "#{User.find_by_id(user.user_id).phone_number} | #{user.receiver}",
						   "#{User.find_by_id(user.user_id).username} | #{User.find_by_phone_number(user.receiver).username}",
						   user.sms_number] %>
		<%= CSV.generate_line row, {:row_sep => nil, :col_sep => ';'} %>
	<% end %>
<% end %>

app/views/users/nombre_de_sms_par_couple.html.erb
<h2 class="top-title">Nombre de sms envoyés par couple</h2>
<br />
<table class="list-table">
  <thead>
    <tr>
      <th width="240">Numéros de téléphone du Couple</th>
      <th>Pseudonymes du couple</th>
      <th>Nombre de sms échangés</th>
    </tr>
  </thead>
  <tbody>
<% unless @users.empty? %>
	<% @users_pagination.each do |user| %>
		<tr>
			<td>
				<%= "#{User.find_by_id(user.user_id).phone_number} | #{user.receiver}" %>
			</td>
			<td>
				<%= "#{User.find_by_id(user.user_id).username} | #{User.find_by_phone_number(user.receiver).username}" %> 
			</td>
			<td>
				<%= user.sms_number %>
			</td>
		</tr>
	<% end %>
<% end %>
  </tbody>
</table>
<div id="pagination">
	<%= will_paginate @users_pagination %>
</div>
<hr />

<%= link_to "Enregistrer", nombre_de_sms_par_couple_path(:csv), :class => 'submit button large ui-corner-all' %>
<%= link_to "Recevoir par mail", sms_par_couple_mail_path, :class => 'submit button large ui-corner-all' %>

app/views/users/nombre_de_sms_par_utilisateur.csv.erb
<% headers = ["NUMERO DE TELEPHONE", "PSEUDONYME", "NOMBRE DE SMS ENVOYES"] %>
<%= CSV.generate_line headers, {:col_sep => ';'} %>
<% pseudo = '' %>
<% unless @users.eql?(nil) %>
	<% @users.each do |user| %>	
		<% if User.find_by_phone_number(user.phone_number).eql?(nil) %>
			<% pseudo = '-' %>
		<% else %>
			<% pseudo = User.find_by_phone_number(user.phone_number).username %> 
		<% end %>
		<% row = [ user.phone_number,
						   pseudo.strip,
						   user.sms_number] %>
		<%= CSV.generate_line row, {:row_sep => nil, :col_sep => ';'} %>
	<% end %>
<% end %>

app/views/users/nombre_de_sms_par_utilisateur.html.erb
<h2 class="top-title">Nombre de sms envoyés par utilisateur</h2>
<br />
<table class="list-table">
  <thead>
    <tr>
      <th width="240">Numéro de téléphone</th>
      <th>Pseudonyme</th>
      <th>Nombre de sms envoyés</th>
    </tr>
  </thead>
  <tbody>
	<% @users_pagination.each do |user| %>
		<tr>
			<td>
				<%= user.phone_number %>
			</td>
			<td>
				<% if User.find_by_phone_number(user.phone_number).eql?(nil) %>
				-
				<% else %>
					<%= User.find_by_phone_number(user.phone_number).username %> 
				<% end %>
			</td>
			<td>
				<%= user.sms_number %>
			</td>
		</tr>
	<% end %>
  </tbody>
</table>
<div id="pagination">
	<%= will_paginate @users_pagination %>
</div>
<hr />

<%= link_to "Enregistrer", nombre_de_sms_par_utilisateur_path(:csv), :class => 'submit button large ui-corner-all' %>
<%= link_to "Recevoir par mail", sms_par_utilisateur_mail_path, :class => 'submit button large ui-corner-all' %>

app/views/users/reports.csv.erb
<% headers = ["Id", "Username", "Age", "Gender"] %>
<%= CSV.generate_line headers, {:col_sep => ';'} %>
<% @users.each do |user| %>
	<% row = [ user.id,
				     user.username,
				     user.age,
				     user.gender] %>
	<%= CSV.generate_line row, {:row_sep => nil, :col_sep => ';'} %>
<% end %>

app/views/users/reports.html.erb
<%= link_to "Export Report", reports_path(:csv) %>
<%= link_to "enregistrer sur le disque", write_to_disk_path %>

app/views/users/stats.html.erb
<%= link_to "envoi de mail", send_email_path %>

<%= link_to "parametres", edit_parameter_path(Parameter.first.id) %>