config/routes.rb
Invisibility::Application.routes.draw do
	
  root :to => "sessions#new"
  resources :administrators
  resources :users
  resource :session
  resources :parameters
  match '/login' => "sessions#new", :as => "login"
	match '/logout' => "sessions#destroy", :as => "logout"
  match '/statistiques' => 'users#stats', :as => :stats
  match '/dashboard' => 'users#stats', :as => :dashboard
  match '/reports' => "users#reports", :as => :reports
  match '/nombre_de_sms_par_utilisateur' => 'users#nombre_de_sms_par_utilisateur', :as => :nombre_de_sms_par_utilisateur
  match '/sms_par_utilisateur_mail' => 'users#nombre_de_sms_par_utilisateur_mail', :as => :sms_par_utilisateur_mail
  match '/nombre_de_sms_par_couple' => 'users#nombre_de_sms_par_couple', :as => :nombre_de_sms_par_couple
  match '/sms_par_couple_mail' => 'users#nombre_de_sms_par_couple_mail', :as => :sms_par_couple_mail
  match '/send_email' => "users#send_email", :as => :send_email
  match '/write_to_disk' => 'users#write_to_disk', :as => :write_to_disk

end

app/models/administrator.rb
require 'digest'

class Administrator < ActiveRecord::Base
	attr_accessor :password
	validates :email, :uniqueness => true,
						:length => { :within => 5..50 },
						:format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }
	validates :password, :confirmation => true
	
	before_save :encrypt_new_password
	
	def self.authenticate(email, password)
		administrator = find_by_email(email)
		return administrator if administrator && administrator.authenticated?(password)
	end
	
	def authenticated?(password)
		self.hashed_password == encrypt(password)
	end
	
	protected
	def encrypt_new_password
		return if password.blank?
		self.hashed_password = encrypt(password)
	end
	
	def password_required?
		hashed_password.blank? || password.present?
	end
	
	def encrypt(string)
		Digest::SHA1.hexdigest(string)
	end
	
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController

	before_filter :authenticate
	
	def new
		@administrator = Administrator.new
		@posts = User.paginate(:page => params[:page], :per_page => 4)
	end
	
	def create
		@administrator = Administrator.new(params[:administrator])
		if @administrator.save
			redirect_to dashboard_path, :notice => 'User successfully added.'
		else
			render :action => 'new'
		end
	end
	
	def edit
		@administrator = Administrator.find(params[:id])
	end
	
	def update
		@administrator = Administrator.find(params[:id])
		if @administrator.update_attributes(params[:administrator])
			redirect_to dashboard_path, :notice => 'Updated user information successfully.'
		else
			render :action => 'edit'
		end
	end
	
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= form_for(@administrator) do |f| %>
	<% if @administrator.errors.any? %>
		<div id="errorExplanation">
			<ul>
				<% @administrator.errors.full_messages.each do |msg| %>	
					<li><%= content_tag :p, msg, :class => 'status info' %></li>
				<% end %>
			</ul>
	</div>
	<% end %>
	<div class="field">
	<%= f.label :email %><br />
	<%= f.text_field :email %>
	</div>
	<div class="field">
	<%= f.label :password %><br />
	<%= f.password_field :password %>
	</div>
	<div class="field">
	<%= f.label :password_confirmation %><br />
	<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
	<%= f.submit 'Valider', :id => 'login-button', :class => 'submit large round' %>
	</div>
<% end %>

<%= will_paginate @posts %>
<% @posts.each do |post| %>
<%= post.username %>
<% end %>

app/views/administrators/edit.html.erb
<h2 class="top-title">Editer votre profil</h2>
<%= render 'form' %>

app/views/administrators/new.html.erb
<h1>New user</h1>
<%= render 'form' %>
<%= link_to 'Back', stats_path %>